---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  labels:
    app.kubernetes.io/part-of: process-control
spec:
  ports:
  - port: 1883
    protocol: TCP
    targetPort: 1883
    name: mqtt
  selector:
    application: mqtt-broker
  type: NodePort