---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mqtt-broker
  labels:
    app.kubernetes.io/name: mqtt-broker
    app.kubernetes.io/part-of: process-control
    application: mqtt-broker
spec:
  selector:
    matchLabels:
      application: mqtt-broker
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mqtt-broker
        app.kubernetes.io/part-of: process-control
        application: mqtt-broker
    spec:
      containers:
        - name: mqtt
          image: quay.io/device-edge-workshops/process-control-mqtt:1.0.0
          ports:
            - containerPort: 1883
              name: mqtt-port
          resources:
            limits:
              memory: 100Mi
              cpu: 100m