---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app.kubernetes.io/name: ui
    app.kubernetes.io/part-of: process-control
    application: ui
spec:
  selector:
    matchLabels:
      application: ui
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ui
        app.kubernetes.io/part-of: process-control
        application: ui
    spec:
      containers:
      - name: ui
        image: quay.io/device-edge-workshops/process-control-ui-k8s:4.0.0
        ports:
          - containerPort: 1880
            name: http-ui-port
        resources:
          limits:
            memory: 250Mi
            cpu: 100m