---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simulate
  labels:
    app.kubernetes.io/name: simulate
    app.kubernetes.io/part-of: process-control
    application: simulate
spec:
  selector:
    matchLabels:
        application: simulate
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simulate
        app.kubernetes.io/part-of: process-control
        application: simulate
    spec:
      containers:
        - name: simulate
          image: quay.io/device-edge-workshops/process-control-simulate-k8s:1.0.0
          resources:
            limits:
              memory: 100Mi
              cpu: 100m